# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3447dedcdd8ad33e0061a90a8048bb32"
name = "LM Theme Sections"
handle = "lm-theme-sections"
application_url = "https://institute-planning-continually-rapidly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "silver-ponies-home-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://institute-planning-continually-rapidly.trycloudflare.com/auth/callback",
  "https://institute-planning-continually-rapidly.trycloudflare.com/auth/shopify/callback",
  "https://institute-planning-continually-rapidly.trycloudflare.com/api/auth/callback",
]

[webhooks]
api_version = "2024-07"

[webhooks.privacy_compliance]
customer_deletion_url = "https://institute-planning-continually-rapidly.trycloudflare.com/api/webhooks/customer_deletion"
customer_data_request_url = "https://institute-planning-continually-rapidly.trycloudflare.com/api/webhooks/customer_request"
shop_deletion_url = "https://institute-planning-continually-rapidly.trycloudflare.com/gdpr_uninstall"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"

[pos]
embedded = false
